.\"Created with GNOME Manpages Editor
.\"http://sourceforge.net/projects/gmanedit2

.\"Replace <program> with the program name, x with the Section Number
.TH "pwmac" 1 "DECEMBER 2016" "jederik" "User Manuals"

.SH NAME
pwmac \- generate domain specific passwords from a master password

..SH SYNOPSIS
.B pwmac [-t 
.I timeout
.B ] [-c] [-l
.I length
.B ] [-s] [-x] 
.I domain
.br
.B pwmac -h

.SH DESCRIPTION
.B pwmac
can be used to generate a password for any domain from a master password.
In contrast to a keystore, it does not save the domain specific passwords on a hard drive, but when given
the same master password and domain descriptor it generates the same domain password.
This prevents the user from having to copy his keystore to every device he uses and from the risk through data loss.

.I domain
can be any string that describes the domain for which a password should be created. For different
domain descriptors
.B pwmac
generates different domain passwords no matter how similar they are and no matter if the master password is the same.

.SS Security Considerations
\fBpwmac\fP uses the \fBopenssl\fP tool to generate a SHA-1 HMAC from \fIdomain\fP using the master password as the key.
The generated MAC is then encoded in \fBbase64\fP and cropped to the desired length.

Note that an attacker who compromises the master password is able to forge \fBany\fP domain password generated with this master password. 
Given the security of the underlying cryptography it is impossible to derive the master password from the generated domain password and/or the domain descriptor. 
It is, however, possible to perform an offline brute force attack on the master password when these two other factors are known.
It is thus of high importance to choose a master password that contains enough entropy to resist a brute force attack.

.SH OPTIONS
.TP  
\fB\-c\fP  
Have the user repeat the master password. This is usefull to beware of typos when setting the password for this domain.

.TP  
\fB\-h\fP  
Print a help text on the screen.

.TP
\fB\-l \fIlength\fP
Specify the length of the generated password. Default is 8.

.TP
\fB\-s\fP
Read master password from stdin and print to stdout only the resulting domain password without prompt or trailing newline.
This option enables using pwmac in pipes, which might come in handy for scripting.

.TP
\fB\-t \fItimeout\fP
Display the generated password for a maximum of \fItimeout\fP seconds on the screen. Default value is 30.

This option is ignored when \fB-x\fP is specified.

.TP  
\fB\-x\fP  
Do not display the generated password on the screen, but instead copy it to the X clipboard. This option requires \fBxclip\fP to be installed.

.SH AUTHOR
Jann-Frederik Laß <jederik@gmail.com>

