#!/bin/bash

# constants
SCRIPT_LOCATION=$(readlink -f "$0")
PWMAC_DIR=$(dirname "$SCRIPT_LOCATION")
USAGE_FILE=$PWMAC_DIR/usage.txt

# default values
length=8
timeout=30

function usage {
	cat $USAGE_FILE
}

# parse options
while getopts ":ht:cxl:s" opt
do
	case $opt in
		h)
			usage
			exit 0
			;;
		t)
			timeout=$OPTARG
			;;
		c)
			confirm=true
			;;
		x)
			silent=true
			;;
		l)
			length=$OPTARG
			;;
		s)
			stdio=true
			;;
		\?)
			echo "Invalid option: -$OPTARG" >&2
			usage
			exit 1
			;;
		:)
			echo "Option -$OPTARG requires an argument" >&2
			usage
			exit 1
			;;
	esac
done

# check requirements
if ! hash openssl 2>/dev/null
then
	echo "openssl missing. pwmac requires openssl." >&2
	exit 1
fi

# check options consistency
if [ "$confirm" = true ] && [ "$stdio" = true ]
then
	echo "Options -s and -c cannot be combined." >&2
	exit 1
fi

# get domain from args
if [ "$#" -ne $OPTIND ];
then
	echo "No domain specified." >&2
	exit 1
fi
shift $((OPTIND-1))
domain=$1

# read master password from stdin
if [ "$stdio" = true ]
then
	read -s password
else
	echo -n "master password: "
	read -s password
	echo
fi

# evtl. confirm master password
if [ "$confirm" = true ]
then
	echo -n "confirm master password: "
	read -s confirmed_password
	echo
	if [ "$confirmed_password" != "$password" ]
	then
		echo "Passwords don't match." >&2
		exit 1
	fi
fi

# generate domain password
domain_pwd=`echo -n "$domain" | openssl dgst -sha1 -hmac "$password" -binary | openssl enc -A -base64 | head -c $length`

# when in pipe mode exit
if [ "$stdio" = true ]
then
	echo -n $domain_pwd
	exit 0
fi

# when in silent mode copy domain password to clipboard
if [ "$silent" = true ]
then
	if ! hash xclip 2>/dev/null
	then
		echo "xclip is not installed. The -x option requires xclip." >&2
		exit 1
	fi
	echo -n "$domain_pwd" | xclip
	echo -n "$domain_pwd" | xclip -selection c
	exit 0
fi

# display domain password
echo -n "$domain_pwd"

# wait for key stroke or timeout
read -t $timeout -s -n1

# remove domain password from screen
echo -ne "\r\033[0K"

